---
version: '3'
services:
  nginx:
    image: nginx:1.22
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist/static:/var/www/static
      # - ./ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      # - "443:443"

  app:
    image: djwanguo:0.1
    command: gunicorn -b 0.0.0.0:8000 -w 2 --access-logfile - --error-logfile - djwanguo.wsgi:application
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
